import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import logo from '../public/vercel.svg'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next Js Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="./favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.logo}>
        <Image src={logo} alt="Vercel Logo" width={72} height={16} />
        </div>

        <h1 className={styles.title}>
          This is the Home Page
        </h1>

        <Link href="/about">About</Link>

        </main>
    </div>
  )
}
